### PR TITLE
added SentenceCase button

### PR DESCRIPTION
**Pull request by dare-devilll**
added Sentencecase.

### CODE REVIEW

**Comment by dare-devilll** [comment]
will the second commit be considered for hacktoberfest?

**Comment by Susmita-Dey** [comment]
@dare-devilll Fix merge conflicts

**Comment by dare-devilll** [comment]
done!

**Review by Susmita-Dey — APPROVED** [review]
Good job. LGTM

**Comment by Susmita-Dey** [comment]
@dare-devilll issue no?

**Comment by dare-devilll** [comment]
issue #15

**Pull request merged**
