### PR TITLE
made change text button

### PR DESCRIPTION
**Pull request by Cypher1002**
i had made issue no #68  this is the implementation 
@Susmita-Dey  could you add it under hacktoberfest tag 

working:-
a button which allows to edit a text from whole paragraph 
for eg:-  if "the" is occurring many times in the text provided but the user needs to change from "the" to "are" everywhere then he could do so just my clicking the button and writing the text once the edit will be implemented everywhere

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Cypher1002 Fix merge conflicts first

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@Cypher1002 pull recent changes. Also, you have messes up with `Start Listening` button. 
image

Fix it

**Comment by Susmita-Dey** [comment]
Why you have committed the `package-lock.json` file?

**Comment by Cypher1002** [comment]
Will fix it

**Comment by Cypher1002** [comment]
@Susmita-Dey  new commits made please review

**Comment by Susmita-Dey** [comment]
> @Cypher1002 You have messes up with `Start Listening` button. image

This issue still lies there as shown in the deploy preview

**Comment by Cypher1002** [comment]
> > @Cypher1002 You have messes up with `Start Listening` button. image
> 
> This issue still lies there as shown in the deploy preview
>

Could i create a new pr please close this one will merge that one

**Comment by Susmita-Dey** [comment]
@Cypher1002 Yes go ahead. I'm closing this one.

**Pull request closed without merging**
