### PR TITLE
Undo/redo the actions performed on the text, resolves Susmita-Dey/Tex…

### PR DESCRIPTION
**Pull request by Ts-A**
…tUtils#84

Undo/Redo Action
1. Use useReducer over useState for maintaing textState due to seperation of complex business logic at a separate place.
2. Undo Button: undo the action performed on the text
3. Redo Button: undo the undone change => undoes what undo action has done
4. Undo and Redo logic  built using undo and redo stack to keep track of the text

### CODE REVIEW

**Comment by Ts-A** [comment]
**After an action is performed:** 
```
RedoStack: []
UndoStack: ['text before 1st action']
text: 'text after first action'
```
TextUtils1

**After a 2nd action is performed:** 
```
RedoStack: []
UndoStack: ['text before 1st action', 'text before 2nd action']
text: 'text after second action'
```
TextUtils2

**After an undo action is performed:** 
```
RedoStack: ['text after second action']
UndoStack: ['text before 1st action',]
text: 'text before 2nd action'
```
TextUtils3

**After a redo action is performed:**
```
RedoStack: []
UndoStack: ['text before 1st action', 'text before 2nd action']
text: 'text after second action'
```
TextUtils4

**Comment by Ts-A** [comment]
Let me know if this works for you.

**Comment by Susmita-Dey** [comment]
@Ts-A Why these buttons are disabled as in the deploy preview?

image

**Comment by Ts-A** [comment]
Did you perform any action on the text? Like convert to uppercase / lowercase

**Comment by Susmita-Dey** [comment]
> Did you perform any action on the text? Like convert to uppercase / lowercase

No

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Great addition.

**Pull request merged**
