### PR TITLE
added Base64 encoding

### PR DESCRIPTION
**Pull request by DarkFalc0n**
Added a button that, when clicked, uses the [Buffer](https://www.npmjs.com/package/buffer) package to encode the given text into [Base64](https://en.wikipedia.org/wiki/Base64).
Referring to Issue #51.
image

### CODE REVIEW

**Comment by DarkFalc0n** [comment]
@Susmita-Dey

**Comment by DarkFalc0n** [comment]
@Susmita-Dey please take action on this pull request it has been open for a long time.

**Comment by Susmita-Dey** [comment]
@DarkFalc0n Fix merge conflicts first

**Comment by DarkFalc0n** [comment]
@Susmita-Dey Please check it now, I have resolved the conflicts.

**Comment by Susmita-Dey** [comment]
@DarkFalc0n pull recent changes

**Comment by DarkFalc0n** [comment]
@Susmita-Dey Done.
Also, can you please take action on the older PRs first beacause otherwise, the older PRs are continuously facing conflicts due to the newer PRs that are being merged.

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Good job

**Pull request merged**
