### PR TITLE
Added cursor pointer

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
Added pr for #5

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 pull once

**Comment by AnshuPathak-88825** [comment]
Didn't get it

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Pull the recent changes to the website. I have merged some PRs just now. It's like updating your branch for this PR

**Comment by AnshuPathak-88825** [comment]
so do I need to make again pr ? @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 No.

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Check this [github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) guide.

**Comment by AnshuPathak-88825** [comment]
I'm not getting it can you tell how can I do it ?

**Comment by Susmita-Dey** [comment]
> I'm not getting it can you tell how can I do it ? @Susmita-Dey

Check the above link github guide

**Comment by slim-codes** [comment]
@AnshuPathak-88825 
Why did you commit **package.json** and **package-lock.json**
Those files shouldn't be staged to when you are committing

**Pull request closed without merging**
