### PR TITLE
Clean code enhancement

### PR DESCRIPTION
**Pull request by Ts-A**
### Major Code Update
Functionality of the overall app remains the same, rather how the data is efficiently and stored is improvised according to the standards.

Pre-requisites
- redux concepts
- @reduxjs/toolkit
- react-redux

Summary of changes
- Removed props that had to be sent down the children component tree unnecessarily. 
- Moved theme, alert and text to a global state.
- Handling data globally and creating actions to be able to get/update data from under the Provider.
- alertMessages.json to better handle alert messages.
- Moved button component to re-usable Button component and called it the required number of times using map.

Future scope for updates

- [ ] Convert .css to modules/ styled components / framework.
- [ ] Make more reusable components.
- [ ] Name the components that serve the route page to PageComponents.
- [ ] Better handle speech functionality.
- [ ] Add count of words, numbers, special characters to global state.
- [ ] Update documentation for redux flow understanding.

### CODE REVIEW

**Comment by Ts-A** [comment]
TextUtils5
TextUtils1
TextUtils2
TextUtils3
TextUtils4

**Comment by Ts-A** [comment]
Hey! @Susmita-Dey could you review my PR!

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by Ts-A** [comment]
@Susmita-Dey fixed conflicts. Kindly review it

**Review by Susmita-Dey — APPROVED** [review]
Great job. Thanks:)

**Comment by Susmita-Dey** [comment]
@Ts-A Kindly close the issue related to this PR.

**Pull request merged**
