### PR TITLE
Change the theme togglers to sun and moon for light and dark theme

### PR DESCRIPTION
**Pull request by tobySolutions**
Hey Susmita!! I made changes to the  Theme toggling and, added an alert message to notify the user when he's about to clear text and I changed the GitHub Link at the bottom hyperlink your name "Susmita Dey" (I really hope this was necessary).

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@tobySolutions Issue no? Was it assigned to you?

Also, your PR has merge conflicts.

**Comment by tobySolutions** [comment]
It says Vercel has issues deploying my changes. 

Yeah, I forgot to ask for assignment of the issue.

**Comment by Susmita-Dey** [comment]
@tobySolutions You have to fix merge conflicts first.

**Comment by tobySolutions** [comment]
susmita's-attention
susmita-attention
I'm seeing these.

**Pull request closed without merging**
