### PR TITLE
Added Bcrypt feature

### LINKED ISSUE #107: Adding new feature to convert the text into Bcrypt hash

### PR DESCRIPTION
**Pull request by dellucifer**
Fixed Issue #107

### CODE REVIEW

**Comment by dellucifer** [comment]
@Susmita-Dey Accept the PR please, and already starred the repo :)

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by dellucifer** [comment]
In package files, the react-scripts are labeled as `"react-scripts": "5.0.1"` but it must be `"react-scripts": "^5.0.1"`. This `^` is missing in the pre-existing file resulting in throwing an error when you clone this repo and run the app using `npm start`.

**Comment by Susmita-Dey** [comment]
> In package files, the react-scripts are labeled as `"react-scripts": "5.0.1"` but it must be `"react-scripts": "^5.0.1"`. This `^` is missing in the pre-existing file resulting in throwing an error when you clone this repo and run the app using `npm start`.

fix it

**Comment by dellucifer** [comment]
Fixed it but it is having conflicts with the main branch, can you please guide me a little bit, I haven't faced conflicts error ever. So, I don't know that much about resolving conflicts.

**Comment by Susmita-Dey** [comment]
@dellucifer Go through this [blog](https://www.freecodecamp.org/news/resolve-merge-conflicts-in-git-a-practical-guide/).

**Pull request closed without merging**
