### PR TITLE
Added Extract text and Numbers Function

### PR DESCRIPTION
**Pull request by Surya8991**
Hi I have added a extract text and numbers function to this play do check it out and merge it.

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@Surya8991 When I'm trying to extract text, it's extracting text along with numbers. What's the use of it then? __

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Surya8991** [comment]
One Sec let me change it

**Comment by Surya8991** [comment]
Should i add reverse text function

**Comment by Surya8991** [comment]
?

**Comment by Susmita-Dey** [comment]
> Should i add reverse text function

Create another PR for that. I'm merging this currently.

**Review by Susmita-Dey — APPROVED** [review]
Thanks for contributing. 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient, Maintainable

**Pull request merged**
