### PR TITLE
Add confirm before clearing the text

### PR DESCRIPTION
**Pull request by shubhamdarwante2301**
confirm by the user before the clear text.
if the user selects "ok" then only text will be deleted.
Screenshot (160)

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@shubhamdarwante2301 In the aove ss, there's a modal at the center of the page but in the deploy preview, it's showing me an alert box. 
Why so? Didn't you made a modal?

**Comment by shubhamdarwante2301** [comment]
@Susmita-Dey  SS is from firefox that's why is showing like this.
it is actually an alert!
did you want a modal?

**Comment by Susmita-Dey** [comment]
@shubhamdarwante2301 Oh I see. Okay leave that.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
