### PR TITLE
changed footer bg color

### PR DESCRIPTION
**Pull request by kumarsanu2002**
Changed footer bg color . It will be dark/black in bright mode, it will differentiate it from all other component .And when dark , mode will be on then its color will match with header. It will look dope , and if you want to  change let me know.

### CODE REVIEW

**Comment by kumarsanu2002** [comment]
merge it

**Comment by Susmita-Dey** [comment]
@kumarsanu2002 issue no?

**Comment by kumarsanu2002** [comment]
@Susmita-Dey  #72

**Comment by kumarsanu2002** [comment]
@Susmita-Dey  If you want any function or changes let me know.

**Comment by Susmita-Dey** [comment]
@kumarsanu2002 I asked for issue no. Not any PR no. Was any issue assigned to you?

**Comment by kumarsanu2002** [comment]
@Susmita-Dey no ,issue was not assigned to me.

**Review by Susmita-Dey — APPROVED** [review]
Closing this as doen't looks good to me

**Pull request closed without merging**
