### PR TITLE
added github link to footer

### PR DESCRIPTION
**Pull request by dare-devilll**
also centered the text in the footer.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@dare-devilll Issue no?

**Comment by dare-devilll** [comment]
Issue #18

**Comment by Susmita-Dey** [comment]
@dare-devilll You have add footer component to the main file otherwise it won't show in the website.

**Comment by dare-devilll** [comment]
I did,Think i forget to save. I will do it.

**Comment by dare-devilll** [comment]
I just checked i have added it.
It's in the sentenceCase pr, it has two commits,
One for sentenceCase and other for footer.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
