### PR TITLE
Firefox speech recognition bug fix

### LINKED ISSUE #99: [Bug] Website crashes on firefox
App crash on firefox

You can see it logs out "undefined is not a constructor".

While in localhost (development), it logs the error "SpeechRecognition is not a constructor".

Cross-browser support needed to be implemented.

### PR DESCRIPTION
**Pull request by aashishpanthi**
#99 Fixed the Website crash on Firefox

Since SpeechRecognition is not supported in Mozilla firefox, I removed the SpeechRecognition feature for the users using Firefox.

I checked if speech recognition is supported or not and conditionally added the feature.

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
Does only formatting the code fixes the issue in Firefox?

**Comment by aashishpanthi** [comment]
> Does only formatting the code fixes the issue in Firefox?

Yes, SpeechRecognition is not supported by firefox. So the website now checks if the SpeechRecognition is supported or not and then allows or disables the feature depending on the result.

Sorry, not only the formatting is done there. SpeechRecognition support is also being checked and the button is being rendered only if the feature is supported.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by aashishpanthi** [comment]
> Fix merge conflicts

Fixed it :)

**Review by Susmita-Dey — APPROVED** [review]
Thanks:)
LGTM

**Pull request merged**
